import { Refine } from "@refinedev/core";
import type { Metadata } from "next";
import React, { Suspense } from "react";
import { RefineContext } from "./_refine_context";
import { createDataProvider } from "@providers/data-provider";
import { ConfigProvider } from "@providers/config-provider";
import config from "@/config";

export const metadata: Metadata = {
	title: "Refine",
	description: "Generated by create refine app",
	icons: {
		icon: "/favicon.ico",
	},
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
		<body>
			<ConfigProvider config={config}>
				<Refine
				dataProvider={createDataProvider("https://api.fake-rest.refine.dev")}
				routerProvider={routerProvider}
				resources={[
					{
						name: "posts",
						list: "/posts",
						show: "/posts/show/:id",
					},
					{
						name: "categories",
						list: "/categories",
						show: "/categories/show/:id",
					},
				]}
				>
				{/* We're defining `Layout` here but you might want to have different layouts per your page. */}
				{/* This is totally fine for Refine, you can place your Layout wherever you like. */}
				<Layout>{children}</Layout>
				</Refine>
			</ConfigProvider>
		</body>
		</html>
	);
//   return (
// 	<html lang="en">
// 		<body>
// 		<Suspense>
// 			<RefineContext>{children}</RefineContext>
// 		</Suspense>
// 		</body>
// 	</html>
//   );
}
