import type { Product } from '../features/product/types';


const createdAt = '2026-01-08T08:00:00.000Z';

export const mockProductsData: Product[] = [
	{
		id: 'prod-1',
		orgId: 'org-1',
		name: { en: 'Premium T-Shirt' },
		sku: 'TSH-001',
		barCode: '8936000000001',
		description: { en: 'Soft cotton t-shirt for daily wear.' },
		thumbnailUrl: 'https://picsum.photos/seed/prod1-main/1200/800',
		unitId: 'uom-1',
		productCategoryIds: ['cat-1'],
		status: 'active',
		attributeIds: ['attr-1', 'attr-2'],
		createdAt,
		updatedAt: createdAt,
		etag: 'etag-prod-1',
	},
	{
		id: 'prod-2',
		orgId: 'org-1',
		name: { en: 'Running Shoes' },
		sku: 'SHO-002',
		barCode: '8936000000002',
		description: { en: 'Lightweight running shoes with stable sole.' },
		thumbnailUrl: 'https://picsum.photos/seed/prod2-main/1200/800',
		unitId: 'uom-1',
		productCategoryIds: ['cat-2'],
		status: 'active',
		attributeIds: ['attr-1', 'attr-3'],
		createdAt,
		updatedAt: createdAt,
		etag: 'etag-prod-2',
	},
	{
		id: 'prod-3',
		orgId: 'org-1',
		name: { en: 'Protein Drink' },
		sku: 'DRK-003',
		barCode: '8936000000003',
		description: { en: 'High-protein beverage for active lifestyle.' },
		thumbnailUrl: 'https://picsum.photos/seed/prod3-main/1200/800',
		unitId: 'uom-6',
		productCategoryIds: ['cat-8'],
		status: 'active',
		attributeIds: ['attr-4', 'attr-5'],
		createdAt,
		updatedAt: createdAt,
		etag: 'etag-prod-3',
	},
	{
		id: 'prod-4',
		orgId: 'org-1',
		name: { en: 'Ergo Office Chair' },
		sku: 'CHR-004',
		barCode: '8936000000004',
		description: { en: 'Ergonomic office chair with lumbar support.' },
		thumbnailUrl: 'https://picsum.photos/seed/prod4-main/1200/800',
		unitId: 'uom-1',
		productCategoryIds: ['cat-6'],
		status: 'active',
		createdAt,
		updatedAt: createdAt,
		etag: 'etag-prod-4',
	},
	{
		id: 'prod-5',
		orgId: 'org-1',
		name: { en: 'Ceramic Mug' },
		sku: 'MUG-005',
		barCode: '8936000000005',
		description: { en: 'Durable ceramic mug for hot and cold drinks.' },
		thumbnailUrl: 'https://picsum.photos/seed/prod5-main/1200/800',
		unitId: 'uom-1',
		productCategoryIds: ['cat-1'],
		status: 'inactive',
		attributeIds: ['attr-2', 'attr-3'],
		createdAt,
		updatedAt: createdAt,
		etag: 'etag-prod-5',
	},
	{
		id: 'prod-6',
		orgId: 'org-1',
		name: { en: 'Wireless Mouse' },
		sku: 'MSE-006',
		barCode: '8936000000006',
		description: { en: 'Silent wireless mouse with ergonomic grip.' },
		thumbnailUrl: 'https://picsum.photos/seed/prod6-main/1200/800',
		unitId: 'uom-1',
		productCategoryIds: ['cat-4'],
		status: 'active',
		createdAt,
		updatedAt: createdAt,
		etag: 'etag-prod-6',
	},
	{
		id: 'prod-7',
		orgId: 'org-1',
		name: { en: 'Notebook A5' },
		sku: 'NTB-007',
		barCode: '8936000000007',
		description: { en: 'A5 notebook with 200 ruled pages.' },
		thumbnailUrl: 'https://picsum.photos/seed/prod7-main/1200/800',
		unitId: 'uom-1',
		productCategoryIds: ['cat-3'],
		status: 'active',
		createdAt,
		updatedAt: createdAt,
		etag: 'etag-prod-7',
	},
	{
		id: 'prod-8',
		orgId: 'org-1',
		name: { en: 'Laundry Detergent' },
		sku: 'DTG-008',
		barCode: '8936000000008',
		description: { en: 'Concentrated laundry detergent liquid.' },
		thumbnailUrl: 'https://picsum.photos/seed/prod8-main/1200/800',
		unitId: 'uom-6',
		productCategoryIds: ['cat-8'],
		status: 'active',
		attributeIds: ['attr-1', 'attr-4'],
		createdAt,
		updatedAt: createdAt,
		etag: 'etag-prod-8',
	},
	{
		id: 'prod-9',
		orgId: 'org-1',
		name: { en: 'Olive Oil' },
		sku: 'OIL-009',
		barCode: '8936000000009',
		description: { en: 'Extra virgin olive oil imported from Italy.' },
		thumbnailUrl: 'https://picsum.photos/seed/prod9-main/1200/800',
		unitId: 'uom-6',
		productCategoryIds: ['cat-8'],
		status: 'inactive',
		createdAt,
		updatedAt: createdAt,
		etag: 'etag-prod-9',
	},
	{
		id: 'prod-10',
		orgId: 'org-1',
		name: { en: 'Shipping Box' },
		sku: 'BOX-010',
		barCode: '8936000000010',
		description: { en: 'Standard shipping box for e-commerce packages.' },
		thumbnailUrl: 'https://picsum.photos/seed/prod10-main/1200/800',
		unitId: 'uom-2',
		productCategoryIds: ['cat-5'],
		status: 'active',
		createdAt,
		updatedAt: createdAt,
		etag: 'etag-prod-10',
	},
];
