import type { Attribute } from '../features/attribute/types';


export const mockAttributesData: Attribute[] = [
	{
		id: 'attr-1',
		productId: 'prod-1',
		codeName: 'color',
		displayName: { en: 'Color' },
		dataType: 'string',
		isEnum: true,
		enumValue: [{ en: 'Red' }, { en: 'Blue' }, { en: 'Black' }, { en: 'White' }],
		isRequired: true,
		sortIndex: 10,
		groupId: 'grp-1',
		enumValueSort: true,
		createdAt: '2026-01-03T08:00:00.000Z',
		updatedAt: '2026-01-03T08:00:00.000Z',
		etag: 'etag-attr-1',
	},
	{
		id: 'attr-2',
		productId: 'prod-1',
		codeName: 'size',
		displayName: { en: 'Size' },
		dataType: 'string',
		isEnum: true,
		enumValue: [{ en: 'Small' }, { en: 'Medium' }, { en: 'Large' }, { en: 'Extra Large' }],
		isRequired: true,
		sortIndex: 20,
		groupId: 'grp-1',
		enumValueSort: true,
		createdAt: '2026-01-03T08:00:00.000Z',
		updatedAt: '2026-01-03T08:00:00.000Z',
		etag: 'etag-attr-2',
	},
	{
		id: 'attr-3',
		productId: 'prod-2',
		codeName: 'material',
		displayName: { en: 'Material' },
		dataType: 'string',
		isEnum: true,
		enumValue: [{ en: 'Cotton' }, { en: 'Polyester' }, { en: 'Leather' }, { en: 'Wood' }],
		isRequired: false,
		sortIndex: 30,
		groupId: 'grp-2',
		enumValueSort: true,
		createdAt: '2026-01-03T08:00:00.000Z',
		updatedAt: '2026-01-03T08:00:00.000Z',
		etag: 'etag-attr-3',
	},
	{
		id: 'attr-4',
		productId: 'prod-3',
		codeName: 'capacity',
		displayName: { en: 'Capacity' },
		dataType: 'string',
		isEnum: true,
		enumValue: [{ en: '250 ml' }, { en: '500 ml' }, { en: '1 Liter' }, { en: '2 Liter' }],
		isRequired: false,
		sortIndex: 40,
		groupId: 'grp-3',
		enumValueSort: true,
		createdAt: '2026-01-03T08:00:00.000Z',
		updatedAt: '2026-01-03T08:00:00.000Z',
		etag: 'etag-attr-4',
	},
	{
		id: 'attr-5',
		productId: 'prod-3',
		codeName: 'flavor',
		displayName: { en: 'Flavor' },
		dataType: 'string',
		isEnum: true,
		enumValue: [{ en: 'Original' }, { en: 'Mint' }, { en: 'Orange' }, { en: 'Berry' }],
		isRequired: false,
		sortIndex: 50,
		groupId: 'grp-3',
		enumValueSort: true,
		createdAt: '2026-01-03T08:00:00.000Z',
		updatedAt: '2026-01-03T08:00:00.000Z',
		etag: 'etag-attr-5',
	},
];
