import { EventProduct } from './types';

// Mock products data
export const mockProducts: EventProduct[] = [
	{
		id: 'prod-1',
		productId: 'prod-1',
		code: 'SP-001',
		name: 'Coca Cola 330ml',
		image: 'https://via.placeholder.com/150?text=Coca+Cola',
		badgeImage: 'https://via.placeholder.com/50?text=NEW',
		originalPrice: 15000,
		eventPrice: 12000,
	},
	{
		id: 'prod-2',
		productId: 'prod-2',
		code: 'SP-002',
		name: 'Pepsi 330ml',
		image: 'https://via.placeholder.com/150?text=Pepsi',
		badgeImage: 'https://via.placeholder.com/50?text=SALE',
		originalPrice: 15000,
		eventPrice: 13000,
	},
	{
		id: 'prod-3',
		productId: 'prod-3',
		code: 'SP-003',
		name: '7Up 330ml',
		image: 'https://via.placeholder.com/150?text=7Up',
		originalPrice: 15000,
		eventPrice: 11000,
	},
	{
		id: 'prod-4',
		productId: 'prod-4',
		code: 'SP-004',
		name: 'Snack Khoai Tây',
		image: 'https://via.placeholder.com/150?text=Snack',
		badgeImage: 'https://via.placeholder.com/50?text=HOT',
		originalPrice: 20000,
		eventPrice: 15000,
	},
	{
		id: 'prod-5',
		productId: 'prod-5',
		code: 'SP-005',
		name: 'Bánh Quy Socola',
		image: 'https://via.placeholder.com/150?text=Cookie',
		originalPrice: 25000,
		eventPrice: 20000,
	},
	{
		id: 'prod-6',
		productId: 'prod-6',
		code: 'SP-006',
		name: 'Nước Suối 500ml',
		image: 'https://via.placeholder.com/150?text=Water',
		originalPrice: 10000,
		eventPrice: 8000,
	},
	{
		id: 'prod-7',
		productId: 'prod-7',
		code: 'SP-007',
		name: 'Kẹo Socola',
		image: 'https://via.placeholder.com/150?text=Candy',
		badgeImage: 'https://via.placeholder.com/50?text=NEW',
		originalPrice: 12000,
		eventPrice: 10000,
	},
	{
		id: 'prod-8',
		productId: 'prod-8',
		code: 'SP-008',
		name: 'Bánh Mì Sandwich',
		image: 'https://via.placeholder.com/150?text=Sandwich',
		originalPrice: 30000,
		eventPrice: 25000,
	},
];
