export const mockModules = [
	{
		key: 'favouritesAndRecentlyUsed',
		label: 'Favourites and Recently Used',
		modules: [
			{
				name: 'Essential',
				slug: 'essential',
				category: 'Essential',
				icon: 'https://static.vecteezy.com/system/resources/previews/056/850/688/non_2x/discord-app-icon-with-transparent-background-free-png.png',
				isDisabled: false,
				isOrphaned: false,
				isFavourite: true,
				lastUsed: '2025-01-01',
			},
			{
				name: 'Identity',
				slug: 'identity',
				category: 'Identity',
				icon: 'icon-identity',
				isDisabled: false,
				isOrphaned: false,
				isFavourite: false,
				lastUsed: '2025-01-01',
			},
			{
				name: 'Inventory',
				slug: 'inventory',
				category: 'Inventory',
				icon: 'icon-inventory',
				isDisabled: false,
				isOrphaned: false,
				isFavourite: false,
				lastUsed: '2025-01-01',
			},
			{
				name: 'Sales',
				slug: 'sales',
				category: 'Sales',
				icon: 'icon-sales',
				isDisabled: false,
				isOrphaned: false,
				isFavourite: false,
				lastUsed: '2025-01-01',
			},
			{
				name: 'Purchase',
				slug: 'purchase',
				category: 'Purchase',
				icon: 'icon-purchase',
				isDisabled: false,
				isOrphaned: false,
				isFavourite: false,
				lastUsed: '2025-01-01',
			},
		],
	},
	{
		key: 'coreBusiness',
		label: 'Core Business Operations (2)',
		modules: [
			{
				name: 'File Drive',
				slug: 'file-drive',
				category: 'File Drive',
				icon: 'icon-file-drive',
				isDisabled: true,
				isFavourite: false,
				lastUsed: '2025-01-01',
			},
			{
				name: 'HR Management',
				slug: 'hr-management',
				category: 'HR Management',
				icon: 'icon-hr-management',
				isDisabled: false,
				isFavourite: false,
				lastUsed: '2025-01-01',
			},
			{
				name: 'Asset Management',
				slug: 'asset-management',
				category: 'Asset Management',
				icon: 'icon-asset-management',
				isDisabled: false,
				isFavourite: false,
				lastUsed: '2025-01-01',
			},
		],
	},
	{
		key: 'communication',
		label: 'Communication (3)',
		modules: [
			{
				name: 'Chat',
				slug: '',
				category: 'communication',
				icon: 'icon-chat',
				isDisabled: false,
				isFavourite: false,
				lastUsed: '2025-01-01',
			},
			{
				name: 'Email',
				slug: 'email',
				category: 'communication',
				icon: 'icon-email',
				isDisabled: false,
				isFavourite: false,
				lastUsed: '2025-01-01',
			},
		],
	},
	{
		key: 'identityAndAccessManagement',
		label: 'Identity & Access Management (1)',
		modules: [
			{
				name: 'Identity',
				slug: 'identity',
				category: 'identityAndAccessManagement',
				icon: 'icon-identity',
				isDisabled: false,
				isFavourite: false,
				lastUsed: '2025-01-01',
			},
		],
	},
	{
		key: 'infomationTechnology',
		label: 'Information Technology (1)',
		modules: [
			{
				name: 'Vending Machine',
				slug: 'vending-machine',
				category: 'infomationTechnology',
				icon: 'icon-vending-machine',
				isDisabled: false,
				isFavourite: false,
				lastUsed: '2025-01-01',
			},
		],
	},
	{
		key: 'inventoryAndLogistics',
		label: 'Inventory & Logistics (1)',
		modules: [
			{
				name: 'Inventory',
				slug: 'inventory',
				category: 'inventoryAndLogistics',
				icon: 'icon-inventory',
				isDisabled: false,
				isFavourite: false,
				lastUsed: '2025-01-01',
			},
			{
				name: 'Purchase',
				slug: 'purchase',
				category: 'inventoryAndLogistics',
				icon: 'icon-purchase',
				isDisabled: false,
				isFavourite: false,
				lastUsed: '2025-01-01',
			},
		],
	},
	{
		key: 'financialManagement',
		label: 'Financial Management (1)',
		modules: [
			{
				name: 'Accounting',
				slug: 'purchase',
				category: 'financialManagement',
				icon: 'icon-accounting',
				isDisabled: false,
				isFavourite: false,
				lastUsed: '2025-01-01',
			},
		],
	},
];